version: '3.7'
networks:
  qrestaurant-network:
    name: qrestaurant-network
    driver: bridge
services:
  qrestaurant-web-app:
    container_name: qrestaurant-web-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    networks:
      - qrestaurant-network
